// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC96sXy3Rl3KsXEiSuhPEV3Et3bwhcbLM4',
    appId: '1:895807068753:android:93ddccf1f1e91acdfdf670',
    messagingSenderId: '895807068753',
    projectId: 'car-rental-app-3ce2b',
    storageBucket: 'car-rental-app-3ce2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYugoDlJyaN3AwR4mFLCewBEjt32lpSA0',
    appId: '1:895807068753:ios:2aee60704f4dfca0fdf670',
    messagingSenderId: '895807068753',
    projectId: 'car-rental-app-3ce2b',
    storageBucket: 'car-rental-app-3ce2b.firebasestorage.app',
    androidClientId: '895807068753-68il7sf36d2cjf4mnjts4eevobj4n7me.apps.googleusercontent.com',
    iosClientId: '895807068753-dm2154qoddm944ngu6m7t02bsaghomc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotifications',
  );
}
